# dclint disable require-project-name-field service-container-name-regex
services:
  mariadb:
    image: mariadb:11@sha256:fcc7fcd7114adb5d41f14d116b8aac45f94280d2babfbbb71b4782922ee6d8d4
    container_name: ${COMPOSE_PROJECT_NAME:?}-mariadb
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/mariadb/data:/var/lib/mysql
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/mariadb/backup:/var/backup/mariadb
    configs:
      - source: mariadb-backup
        target: /usr/local/bin/db-backup
      - source: mariadb-init
        target: /usr/local/bin/db-init
    secrets:
      - mariadb-password
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-password
    command:
      - --innodb-buffer-pool-size=512M
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      #- --max-connections=512
      - --innodb-rollback-on-timeout=OFF
      - --innodb-lock-wait-timeout=120
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - deck-chores.backup.command=/usr/local/bin/db-backup
      - deck-chores.backup.cron=*/12 0 0
      - deck-chores.backup.jitter=120m
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "3306"
    init: true
    security_opt:
      # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    stop_grace_period: 5s

secrets:
  mariadb-password:
    environment: MARIADB_ROOT_PASSWORD

configs:
  mariadb-backup:
    file: db-backup
  mariadb-init:
    file: db-init
