SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
SYMFONY__ENV__DATABASE_HOST=postgres
SYMFONY__ENV__DATABASE_NAME=wallabag
SYMFONY__ENV__DATABASE_PASSWORD={{ op://Applications/POSTGRES_WALLABAG/password }}
SYMFONY__ENV__DATABASE_PORT=5432
SYMFONY__ENV__DATABASE_USER={{ op://Applications/POSTGRES_WALLABAG/username }}
SYMFONY__ENV__DOMAIN_NAME=https://wallabag.{{ op://Applications/PROXY/DOMAIN }}
