# dclint disable require-project-name-field service-container-name-regex
services:
  postgres:
    image: docker.io/postgres:17@sha256:864831322bf2520e7d03d899b01b542de6de9ece6fe29c89f19dc5e1d5568ccf
    container_name: ${COMPOSE_PROJECT_NAME:?}-postgres
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/postgres:/var/lib/postgresql/data
    configs:
      - source: postgres_db-backup
        target: /usr/local/bin/db-backup
      - source: postgres_db-init
        target: /usr/local/bin/db-init
    secrets:
      - postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "5432"
    init: true

secrets:
  postgres_password:
    environment: POSTGRES_ROOT_PASSWORD

configs:
  postgres_db-backup:
    file: db-backup
  postgres_db-init:
    file: db-init
