name: apps

include:
  - path: common/compose.postgres.yaml
  - path: common/compose.mariadb.yaml

services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.13@sha256:199c67ed55bfb9d58bf90db2ee280880ae9ebc63413e54c73522f9c4ebdc7bad
    container_name: paperless
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/paperless:/config
      - nfs-documents:/documents
    secrets:
      - paperless-dbpass
    environment:
      PAPERLESS_CONSUMER_POLLING: "30"
      PAPERLESS_PORT: "8000"
      PAPERLESS_URL: https://paperless.${DOMAIN:?}
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBPASS_FILE: /run/secrets/paperless-dbpass
      PAPERLESS_DATA_DIR: /config/data
      PAPERLESS_MEDIA_ROOT: /documents
      PAPERLESS_CONSUMPTION_DIR: /documents/_processed
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_DATE_ORDER: MDY
      PAPERLESS_TASK_WORKERS: "2"
      PAPERLESS_THREADS_PER_WORKER: "2"
      PAPERLESS_EMAIL_TASK_CRON: "disable"
      PAPERLESS_ENABLE_COMPRESSION: "0"
      PAPERLESS_WEBSERVER_WORKERS: "2"
      USERMAP_UID: "3005"
      USERMAP_GID: "100"
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 24M
        limits:
          memory: 1Gi
    expose:
      - 8000
    init: true

  pdf-web-edit:
    image: registry-1.docker.io/lbrowning/pdf-web-edit:v0.9.0@sha256:a385abf0528fd28a0a1c855548a2f9cf1372d3498d03af1ab70a89e06b49ab70
    container_name: pdf-web-edit
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/pdf-web-edit:/config
      - source: nfs-documents
        target: /inbox
        type: volume
        volume:
          subpath: _inbox
      - source: nfs-documents
        target: /outbox
        type: volume
        volume:
          subpath: _processed
      - source: nfs-documents
        target: /archive
        type: volume
        volume:
          subpath: _rejected
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 24M
        limits:
          memory: 96M
    expose:
      - 80
    init: false

  photoprism:
    image: registry-1.docker.io/photoprism/photoprism:20220121@sha256:8dd9e8e5290c8bf648d0e91ea8ef81038ffc8800ebf6322417682a0342e04065
    container_name: photoprism
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/photoprism/env
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 128M
        limits:
          memory: 2G
    expose:
      - 2342
    init: false

  redis:
    image: redis:alpine@sha256:ea9fcb1c25a20121af8a57d42cd5fea83d3b2cbb497a993f2a15265e0d59043e
    container_name: redis
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/redis:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 20s
      timeout: 3s
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - 6379
    init: true

networks:
  default:
    name: global

volumes:
  nfs-documents:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/documents"

secrets:
  paperless-dbpass:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/paperless/dbpass
