name: home-automation

include:
  - path: common/compose.postgres.yaml # home-assistant database

services:
  go2rtc:
    image: alexxit/go2rtc@sha256:eafcc3bad6c24ebc6d349c8c98a72b5cd5145d8f580452aed9fec20da9e6c6dd
    container_name: go2rtc
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/go2rtc:/config
    ports:
      # rtsp
      - "8554:8554"
      # webrtc
      - "8555:8555"
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.go2rtc.loadbalancer.server.port=1984
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 32M
        limits:
          memory: 64M
    expose:
      - "1984"
    init: false

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2025.2@sha256:9bde98a5c314a1d0bef07d6ab7bc36c2abf98df6337ca36db4e57adeeda1dc79
    container_name: home-assistant
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/home-assistant:/config
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - --config
      - /config
    entrypoint:
      - exec
      - python3
      - -m
      - homeassistant
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.home-assistant.loadbalancer.server.port=8123
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
      - metrics-job=home-assistant
      - scrape-port=8123
      - scrape-path=/api/prometheus
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 1G
    expose:
      - "8123"
    init: true

  mosquitto:
    image: registry-1.docker.io/library/eclipse-mosquitto:2.0.20@sha256:deae95623b9d5c6ca5e264380629db53b992106d436b56d42f7c8df46b41b96f
    container_name: mosquitto
    ports:
      - "1883:1883"
    networks:
      - default
    command:
      - -c
      - /mosquitto-no-auth.conf
    entrypoint:
      - mosquitto
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 16M
        limits:
          memory: 64M
    init: true

  tasmoadmin:
    image: ghcr.io/tasmoadmin/tasmoadmin:v4.2.2@sha256:1cebfcd97836b197085df8923eb8730a119b3f59793248f4914e2a3919e84476
    container_name: tasmoadmin
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/tasmoadmin:/data
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 32M
        limits:
          memory: 64M
    expose:
      - "80"
    init: false

  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.1.1@sha256:c7b111384716247f057b449ebb242bf05f3fafb98dd6d5688c1ac1fc730d5e95
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/zigbee2mqtt:/app/data
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    devices:
      - ${ZIGBEE_DEVICE:?}:/dev/zigbee
    expose:
      - "8080"
    init: true

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:?}
  proxy-home-automation:
    name: proxy-home-automation
