name: media

include:
  - path: common/compose.postgres.yaml

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.18.1@sha256:39dc3c2243647f7c44f4cf847bc97c8854cf52c01059b0ea7d59ce10242cab4b
    container_name: audiobookshelf
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/config:/config
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/metadata:/metadata
      - nfs-podcasts:/podcasts
    environment:
      - PORT=13378
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=13378
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 1.5G
    expose:
      - "13378"
    init: true

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.5.1@sha256:67039e2dc98163bfdff8c3c1fbb79f75649c8f28b447f5308fcf762a5572f19c
    container_name: bazarr
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/bazarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
      - nfs-television:/media/television
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - --no-update=true
      - --config=/config
    entrypoint:
      - python3
      - /app/bazarr/bin/bazarr.py
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "6767"
    init: true

  bazarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: bazarr-exporter
    secrets:
      - bazarr-api-key
    environment:
      - PORT=9707
      - URL=http://bazarr:6767
      - API_KEY_FILE=/run/secrets/bazarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - bazarr
    restart: unless-stopped
    labels:
      - metrics-job=bazarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  lidarr:
    image: ghcr.io/linuxserver/lidarr:2.8.2@sha256:53c20797ec7fc800a91660bebaed498b7446c029a5086a5c017418d4913096be
    container_name: lidarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/lidarr:/config
      - nfs-music:/media/music
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/lidarr/bin/Lidarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: .25G
        limits:
          memory: 2G
    expose:
      - "8686"
    init: true

  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: lidarr-exporter
    depends_on:
      - lidarr
    secrets:
      - lidarr-api-key
    environment:
      - PORT=9707
      - URL=http://lidarr:8686
      - API_KEY_FILE=/run/secrets/lidarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - lidarr
    restart: unless-stopped
    labels:
      - metrics-job=lidarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.29.2@sha256:0260e79efd04a68ab3c9e428bd347e6c4c57860d534628e437911ed7c5868479
    container_name: prowlarr
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/prowlarr:/config
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/prowlarr/bin/Prowlarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 512M
    expose:
      - "9696"
    init: true

  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: prowlarr-exporter
    depends_on:
      - prowlarr
    secrets:
      - prowlarr-api-key
    environment:
      - PORT=9707
      - URL=http://prowlarr:9696
      - API_KEY_FILE=/run/secrets/prowlarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - prowlarr
    restart: unless-stopped
    labels:
      - metrics-job=prowlarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9709"
    init: false

  radarr:
    image: ghcr.io/linuxserver/radarr:5.17.2@sha256:7a25facfb3e08c9f57cee1ffd995141de80587be1b038bba5fa8611c2355225a
    container_name: radarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/radarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/radarr/bin/Radarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G
    expose:
      - "7878"
    init: true

  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: radarr-exporter
    depends_on:
      - radarr
    secrets:
      - radarr-api-key
    environment:
      - PORT=9707
      - URL=http://radarr:7878
      - API_KEY_FILE=/run/secrets/radarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - radarr
    restart: unless-stopped
    labels:
      - metrics-job=radarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:4.4.1@sha256:5f323d7c2c67f700f8c0e40f25bf3d67c03c35b65c82a1c1680fcb0d055f6528
    container_name: sabnzbd
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sabnzbd:/config
      - nfs-downloads:/downloads
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - --config-file
      - /config/sabnzbd.ini
      - -l1
    entrypoint:
      - python3
      - /app/sabnzbd/SABnzbd.py
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 128M
        limits:
          memory: 1G
    expose:
      - "8080"
    init: true

  sabnzbd-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: sabnzbd-exporter
    depends_on:
      - sabnzbd
    secrets:
      - sabnzbd-api-key
    environment:
      - PORT=9707
      - URL=http://sabnzbd:8080
      - API_KEY_FILE=/run/secrets/sabnzbd-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - sabnzbd
    restart: unless-stopped
    labels:
      - metrics-job=sabnzbd
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.12@sha256:ca71add37a9cdbb914c7bd5b06f98bf5d2062848c8de6ac3ee09e69a4c170b27
    container_name: sonarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sonarr:/config
      - nfs-downloads:/downloads
      - nfs-television:/media/television
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/sonarr/bin/Sonarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G
    expose:
      - "8989"
    init: true

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: sonarr-exporter
    depends_on:
      - sonarr
    secrets:
      - sonarr-api-key
    environment:
      - PORT=9707
      - URL=http://sonarr:8989
      - API_KEY_FILE=/run/secrets/sonarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - sonarr
    restart: unless-stopped
    labels:
      - metrics-job=sonarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  yt-dlp:
    image: ghcr.io/jauderho/yt-dlp:latest@sha256:99b084ac45a9302a731407552b8f2d627295c5ecbab05ad86097392e883ced1a
    container_name: yt-dlp
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/ytdlp:/config
      - nfs-downloads:/downloads
      - nfs-internet:/internet
    networks:
      - default
    entrypoint:
      - sleep
      - infinity
    restart: unless-stopped
    labels:
      - chadburn.enabled=true
      - chadburn.job-exec.yt-dlp.schedule=@every 12h
      - chadburn.job-exec.yt-dlp.command=/config/scheduled-task
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 500M
        limits:
          memory: 1G
    init: true

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:?}
  proxy-media:
    name: proxy-media

volumes:
  nfs-downloads:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/downloads"
  nfs-internet:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/internet"
  nfs-movies:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/movies"
  nfs-music:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/music"
  nfs-television:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/television"
  nfs-podcasts:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/podcasts"

secrets:
  bazarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/bazarr-api-key
  lidarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/lidarr-api-key
  prowlarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/prowlarr-api-key
  radarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/radarr-api-key
  sabnzbd-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/sabnzbd-api-key
  sonarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/sonarr-api-key
