name: media

include:
  - common/compose.postgres.yaml

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.16.2@sha256:e0daed86091611573f5c9f6847608badb5a302659ed3f8ddf0fb0c8e9901a59c
    container_name: audiobookshelf
    restart: unless-stopped
    init: true
    expose:
      - 13378
    environment:
      - PORT=13378
    labels:
      - traefik.enable=true
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=13378
    volumes:
      - "${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/config:/config"
      - "${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/metadata:/metadata"
      - nfs-podcasts:/podcasts
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 1.5G

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.4.5@sha256:88684337f4e3ea6c47623e47c5c27f798ed0d24fbca3e08c8d04be7a2b8a5668
    container_name: bazarr
    restart: unless-stopped
    init: true
    expose:
      - 6767
    labels:
      - traefik.enable=true
    entrypoint:
      - python3
      - /app/bazarr/bin/bazarr.py
    command:
      - --no-update=true
      - --config=/config
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/bazarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
      - nfs-television:/media/television
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 512M

  bazarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: bazarr-exporter
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    command:
      - bazarr
    expose:
      - 9707
    environment:
      - PORT=9707
      - URL=http://bazarr:6767
      - API_KEY_FILE=/run/secrets/bazarr-api-key
    secrets:
      - bazarr-api-key
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M

  lidarr:
    image: ghcr.io/linuxserver/lidarr:2.7.1@sha256:c4d9107e03efb0d73bd4491bdb3110fa497da8b53493f60404fbd53087ff0119
    container_name: lidarr
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    entrypoint:
      - /app/lidarr/bin/Lidarr
    command:
      - -nobrowser
      - -data=/config
    expose:
      - 8686
    volumes:
      - "${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/lidarr:/config"
      - nfs-music:/media/music
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: .25G
        limits:
          memory: 2G

  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: lidarr-exporter
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    command:
      - lidarr
    environment:
      - PORT=9707
      - URL=http://lidarr:8686
      - API_KEY_FILE=/run/secrets/lidarr-api-key
    expose:
      - 9707
    secrets:
      - lidarr-api-key
    depends_on:
      - lidarr
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.25.4@sha256:295528cb3a94c96871b1e90f690668fc267738116be6383ee14f044468f1eed3
    container_name: prowlarr
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    entrypoint:
      - /app/prowlarr/bin/Prowlarr
    command:
      - -nobrowser
      - -data=/config
    expose:
      - 9696
    volumes:
      - "${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/prowlarr:/config"
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 512M

  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: prowlarr-exporter
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    command:
      - prowlarr
    expose:
      - 9709
    environment:
      - PORT=9707
      - URL=http://prowlarr:9696
      - API_KEY_FILE=/run/secrets/prowlarr-api-key
    secrets:
      - prowlarr-api-key
    depends_on:
      - prowlarr
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M

  radarr:
    image: ghcr.io/linuxserver/radarr:5.14.0@sha256:3329fbf778701cf53703b342b3a84da31caafec970ef9310be5723dd057666dc
    container_name: radarr
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    entrypoint:
      - /app/radarr/bin/Radarr
    command:
      - -nobrowser
      - -data=/config
    expose:
      - 7878
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/radarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G

  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: radarr-exporter
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    command:
      - radarr
    expose:
      - 9707
    environment:
      - PORT=9707
      - URL=http://radarr:7878
      - API_KEY_FILE=/run/secrets/radarr-api-key
    secrets:
      - radarr-api-key
    depends_on:
      - radarr
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:4.3.3@sha256:5ae714b1a941a38471c2cc381ec407f93b3d7823c5a77a9a651502036b70ad69
    container_name: sabnzbd
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    entrypoint:
      - python3
      - /app/sabnzbd/SABnzbd.py
    command:
      - --config-file
      - /config/sabnzbd.ini
      - -l1
    expose:
      - 8080
    volumes:
      - "${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sabnzbd:/config"
      - nfs-downloads:/downloads
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 128M
        limits:
          memory: 1G

  sabnzbd-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: sabnzbd-exporter
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    command:
      - sabnzbd
    expose:
      - 9707
    environment:
      - PORT=9707
      - URL=http://sabnzbd:8080
      - API_KEY_FILE=/run/secrets/sabnzbd-api-key
    secrets:
      - sabnzbd-api-key
    depends_on:
      - sabnzbd
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.10@sha256:c0281bd62b9a75f088fa4a09e5f8776431921883766633cb5e5fbd5a74761155
    container_name: sonarr
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    entrypoint:
      - /app/sonarr/bin/Sonarr
    command:
      - -nobrowser
      - -data=/config
    expose:
      - 8989
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sonarr:/config
      - nfs-downloads:/downloads
      - nfs-television:/media/television
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    container_name: sonarr-exporter
    restart: unless-stopped
    init: true
    labels:
      - traefik.enable=true
    command:
      - sonarr
    expose:
      - 9707
    environment:
      - PORT=9707
      - URL=http://sonarr:8989
      - API_KEY_FILE=/run/secrets/sonarr-api-key
    secrets:
      - sonarr-api-key
    depends_on:
      - sonarr
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M

  yt-dlp:
    image: ghcr.io/jauderho/yt-dlp:latest@sha256:3cd6e19c5f03515a2f1e19501eda4cf89474e1ba4c98860ad382acb33e44d377
    container_name: yt-dlp
    restart: unless-stopped
    init: true
    entrypoint:
      - sleep
      - infinity
    labels:
      - chadburn.enabled=true
      - chadburn.job-exec.yt-dlp.schedule=@every 12h
      - chadburn.job-exec.yt-dlp.command=/config/scheduled-task
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/ytdlp:/config
      - nfs-internet:/downloads
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 500M
        limits:
          memory: 1G

secrets:
  bazarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/bazarr-api-key
  lidarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/lidarr-api-key
  prowlarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/prowlarr-api-key
  radarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/radarr-api-key
  sabnzbd-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/sabnzbd-api-key
  sonarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/sonarr-api-key

volumes:
  nfs-downloads:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/downloads"
  nfs-internet:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/internet"
  nfs-movies:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/movies"
  nfs-music:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/music"
  nfs-television:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/television"
  nfs-podcasts:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/podcasts"
