name: media

include:
  - path: common/compose.postgres.yaml

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.20.0@sha256:8901592931b7b2c95fa336664ddf4b9df6260bfce8aacca23c4fc6c2b2f08109
    container_name: audiobookshelf
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/config:/config
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/metadata:/metadata
      - nfs-podcasts:/podcasts
    environment:
      - PORT=13378
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=13378
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 1.5G
    expose:
      - "13378"
    init: true

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.5.1@sha256:b98bdcac54db7ed05524fb63447b855d7fc419428222b3827b1cc9655f95bf51
    container_name: bazarr
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/bazarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
      - nfs-television:/media/television
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - --no-update=true
      - --config=/config
    entrypoint:
      - python3
      - /app/bazarr/bin/bazarr.py
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "6767"
    init: true

  bazarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.1.0@sha256:ffe2065573db0f9717443143316eac6b335c37e6f6fea2f6a238ef3f134ee50a
    container_name: bazarr-exporter
    secrets:
      - bazarr-api-key
    environment:
      - PORT=9707
      - URL=http://bazarr:6767
      - API_KEY_FILE=/run/secrets/bazarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - bazarr
    restart: unless-stopped
    labels:
      - metrics-job=bazarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  lidarr:
    image: ghcr.io/linuxserver/lidarr:2.10.3@sha256:a6a7991f217f3c8b2bfffce1eb962e84b7ecd3cf7869f1456af54d0551bac9b7
    container_name: lidarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/lidarr:/config
      - nfs-music:/media/music
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/lidarr/bin/Lidarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: .25G
        limits:
          memory: 2G
    expose:
      - "8686"
    init: true

  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.1.0@sha256:ffe2065573db0f9717443143316eac6b335c37e6f6fea2f6a238ef3f134ee50a
    container_name: lidarr-exporter
    depends_on:
      - lidarr
    secrets:
      - lidarr-api-key
    environment:
      - PORT=9707
      - URL=http://lidarr:8686
      - API_KEY_FILE=/run/secrets/lidarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - lidarr
    restart: unless-stopped
    labels:
      - metrics-job=lidarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.33.3@sha256:e6afa0c106a24fc3cb90df825956908bb5070cdae9d8b9595fb998b9e0e08d2c
    container_name: prowlarr
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/prowlarr:/config
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/prowlarr/bin/Prowlarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 512M
    expose:
      - "9696"
    init: true

  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.1.0@sha256:ffe2065573db0f9717443143316eac6b335c37e6f6fea2f6a238ef3f134ee50a
    container_name: prowlarr-exporter
    depends_on:
      - prowlarr
    secrets:
      - prowlarr-api-key
    environment:
      - PORT=9707
      - URL=http://prowlarr:9696
      - API_KEY_FILE=/run/secrets/prowlarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - prowlarr
    restart: unless-stopped
    labels:
      - metrics-job=prowlarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9709"
    init: false

  radarr:
    image: ghcr.io/linuxserver/radarr:5.21.1@sha256:5ad8df1b0dc0bb0c2232a9278b85c3c230d82184415f83238b5969da8dc6a942
    container_name: radarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/radarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/radarr/bin/Radarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G
    expose:
      - "7878"
    init: true

  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.1.0@sha256:ffe2065573db0f9717443143316eac6b335c37e6f6fea2f6a238ef3f134ee50a
    container_name: radarr-exporter
    depends_on:
      - radarr
    secrets:
      - radarr-api-key
    environment:
      - PORT=9707
      - URL=http://radarr:7878
      - API_KEY_FILE=/run/secrets/radarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - radarr
    restart: unless-stopped
    labels:
      - metrics-job=radarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:4.5.1@sha256:4087a051fa3aec7c320db624f572eba71513bcb34b146fbd036b8c7c92b78bfa
    container_name: sabnzbd
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sabnzbd:/config
      - nfs-downloads:/downloads
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - --config-file
      - /config/sabnzbd.ini
      - -l1
    entrypoint:
      - python3
      - /app/sabnzbd/SABnzbd.py
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 128M
        limits:
          memory: 1G
    expose:
      - "8080"
    init: true

  sabnzbd-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.1.0@sha256:ffe2065573db0f9717443143316eac6b335c37e6f6fea2f6a238ef3f134ee50a
    container_name: sabnzbd-exporter
    depends_on:
      - sabnzbd
    secrets:
      - sabnzbd-api-key
    environment:
      - PORT=9707
      - URL=http://sabnzbd:8080
      - API_KEY_FILE=/run/secrets/sabnzbd-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - sabnzbd
    restart: unless-stopped
    labels:
      - metrics-job=sabnzbd
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.14@sha256:cefa1c97ba8f5db60c1c89d04015ead764d3b850b4fbdc5784bdde2a02d72350
    container_name: sonarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sonarr:/config
      - nfs-downloads:/downloads
      - nfs-television:/media/television
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/sonarr/bin/Sonarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-${COMPOSE_PROJECT_NAME:?}
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G
    expose:
      - "8989"
    init: true

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.1.0@sha256:ffe2065573db0f9717443143316eac6b335c37e6f6fea2f6a238ef3f134ee50a
    container_name: sonarr-exporter
    depends_on:
      - sonarr
    secrets:
      - sonarr-api-key
    environment:
      - PORT=9707
      - URL=http://sonarr:8989
      - API_KEY_FILE=/run/secrets/sonarr-api-key
    networks:
      - default
      - proxy-${COMPOSE_PROJECT_NAME:?}
    command:
      - sonarr
    restart: unless-stopped
    labels:
      - metrics-job=sonarr
      - scrape-port=9707
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "9707"
    init: false
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:2025.04.18@sha256:7fb30256183d2240d0050651916add9b71431dc6688eafb87df3afb2d0aeed61
    container_name: ytdl-sub
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/ytdl-sub:/config
      - nfs-downloads:/downloads
      - nfs-internet:/internet
    environment:
      - PUID=3005
      - PGID=100
      - TZ=America/Los_Angeles
    networks:
      - default
    entrypoint:
      - sleep
      - infinity
    restart: unless-stopped
    labels:
      - chadburn.enabled=true
      - chadburn.job-exec.yt-dlp.schedule=@every 12h
      - chadburn.job-exec.yt-dlp.command=/config/scheduled-task
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 500M
        limits:
          memory: 1G
    init: false

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:?}
  proxy-media:
    name: proxy-media

volumes:
  nfs-downloads:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/downloads"
  nfs-internet:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/internet"
  nfs-movies:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/movies"
  nfs-music:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/music"
  nfs-television:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/television"
  nfs-podcasts:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/podcasts"

secrets:
  bazarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/bazarr-api-key
  lidarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/lidarr-api-key
  prowlarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/prowlarr-api-key
  radarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/radarr-api-key
  sabnzbd-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/sabnzbd-api-key
  sonarr-api-key:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/sonarr-api-key
