name: monitoring

services:
  dozzle:
    image: amir20/dozzle:v8@sha256:7ba6766590e4a6a7b20676a29697666b37f9871d26283e91bcbf18c609fa70a9
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 16M
        limits:
          memory: 64M
    expose:
      - "8080"

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    secrets:
      - grafana_admin_password
      - source: pagerduty_integration_key
        target: pagerduty_integration_key
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN:?}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_UNIFIED_ALERTING_ENABLED=true
      - PAGERDUTY_INTEGRATION_KEY__FILE=/run/secrets/pagerduty_integration_key
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 128M
        limits:
          memory: 256M
    expose:
      - "3000"

  metrics:
    image: registry-1.docker.io/victoriametrics/victoria-metrics:v1.119.0@sha256:393cd7b4062f9e1cfc9a3b6a3dae74820e4b30ee5c4fe3af7ab2687aad8bceb5
    container_name: metrics
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/metrics:/storage
    configs:
      - source: scrape-configs
        target: /config/prometheus.yaml
    command:
      - -retentionPeriod=${METRICS_RETENTION:-30d}
      - -promscrape.config=/config/prometheus.yaml
      - -storageDataPath=/storage
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "8428"

  push-monitor:
    image: curlimages/curl:8.11.0
    container_name: push-monitor
    command:
      [
        "sh",
        "-c",
        "while true; do curl -fsS $PUSH_MONITOR_URL || true; sleep 60; done"
      ]
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 8M
        limits:
          memory: 16M

secrets:
  grafana_admin_password:
    file: ${GRAFANA_ADMIN_PASSWORD_FILE}
  pagerduty_integration_key:
    file: ${PAGERDUTY_INTEGRATION_KEY_FILE}

configs:
  scrape-configs:
    file: scrape-configs.yaml
