name: monitoring

services:
  dozzle:
    image: amir20/dozzle:v8@sha256:b6791e8893adce2ea73512b618e0bca2370e77f1ef32848bf6478663633cc31d
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 16M
        limits:
          memory: 64M
    expose:
      - "8080"

  grafana:
    image: grafana/grafana:12.1.0@sha256:6ac590e7cabc2fbe8d7b8fc1ce9c9f0582177b334e0df9c927ebd9670469440f
    container_name: grafana
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    secrets:
      - grafana_admin_password
      - source: pagerduty_integration_key
        target: pagerduty_integration_key
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN:?}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_UNIFIED_ALERTING_ENABLED=true
      - PAGERDUTY_INTEGRATION_KEY__FILE=/run/secrets/pagerduty_integration_key
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 128M
        limits:
          memory: 256M
    expose:
      - "3000"

  metrics:
    image: registry-1.docker.io/victoriametrics/victoria-metrics:v1.123.0@sha256:e47c14e6bacd79eaa05a032f263dca91a157f1618de65f8f1f1617e44ebd3757
    container_name: metrics
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/metrics:/storage
    configs:
      - source: scrape-configs
        target: /config/prometheus.yaml
    command:
      - -retentionPeriod=${METRICS_RETENTION:-30d}
      - -promscrape.config=/config/prometheus.yaml
      - -storageDataPath=/storage
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "8428"

  push-monitor:
    image: curlimages/curl:8.15.0@sha256:4026b29997dc7c823b51c164b71e2b51e0fd95cce4601f78202c513d97da2922
    container_name: push-monitor
    command:
      [
        "sh",
        "-c",
        "while true; do curl -fsS $PUSH_MONITOR_URL || true; sleep 60; done"
      ]
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 8M
        limits:
          memory: 16M

  meshcentral:
    image: ghcr.io/ylianst/meshcentral:latest
    container_name: meshcentral
    environment:
      - HOSTNAME=meshcentral.${DOMAIN}
      - ALLOW_NEW_ACCOUNTS=false
      - USE_MONGODB=false
      - PROMETHEUS=9464
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/meshcentral/data:/opt/meshcentral/meshcentral-data
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/meshcentral/files:/opt/meshcentral/meshcentral-files
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/meshcentral/web:/opt/meshcentral/meshcentral-web
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/meshcentral/backups:/opt/meshcentral/meshcentral-backups
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.meshcentral.rule=Host(`meshcentral.${DOMAIN}`)
      - traefik.http.services.meshcentral.loadbalancer.server.port=443
      - traefik.http.routers.meshcentral.tls=true
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: 256M
        limits:
          memory: 512M
    expose:
      - "443"
      - "9464"

secrets:
  grafana_admin_password:
    file: ${GRAFANA_ADMIN_PASSWORD_FILE}
  pagerduty_integration_key:
    file: ${PAGERDUTY_INTEGRATION_KEY_FILE}

configs:
  scrape-configs:
    file: scrape-configs.yaml
