name: monitoring

services:
  dozzle:
    image: amir20/dozzle:v8@sha256:36707d180462e764eac81aac793f8352296048404fa4dea1f280fa3cefa7fce3
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 16M
        limits:
          memory: 64M
    expose:
      - "8080"

  grafana:
    image: grafana/grafana:12.0.2@sha256:b5b59bfc7561634c2d7b136c4543d702ebcc94a3da477f21ff26f89ffd4214fa
    container_name: grafana
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    secrets:
      - grafana_admin_password
      - source: pagerduty_integration_key
        target: pagerduty_integration_key
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN:?}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_UNIFIED_ALERTING_ENABLED=true
      - PAGERDUTY_INTEGRATION_KEY__FILE=/run/secrets/pagerduty_integration_key
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 128M
        limits:
          memory: 256M
    expose:
      - "3000"

  metrics:
    image: registry-1.docker.io/victoriametrics/victoria-metrics:v1.121.0@sha256:4f65d40da793ee125f7fbf9f882114520b0168949c4b9fb2c11403168d9dc3f9
    container_name: metrics
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/metrics:/storage
    configs:
      - source: scrape-configs
        target: /config/prometheus.yaml
    command:
      - -retentionPeriod=${METRICS_RETENTION:-30d}
      - -promscrape.config=/config/prometheus.yaml
      - -storageDataPath=/storage
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    expose:
      - "8428"

  push-monitor:
    image: curlimages/curl:8.14.1@sha256:9a1ed35addb45476afa911696297f8e115993df459278ed036182dd2cd22b67b
    container_name: push-monitor
    command:
      [
        "sh",
        "-c",
        "while true; do curl -fsS $PUSH_MONITOR_URL || true; sleep 60; done"
      ]
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 8M
        limits:
          memory: 16M

secrets:
  grafana_admin_password:
    file: ${GRAFANA_ADMIN_PASSWORD_FILE}
  pagerduty_integration_key:
    file: ${PAGERDUTY_INTEGRATION_KEY_FILE}

configs:
  scrape-configs:
    file: scrape-configs.yaml
