name: media

include:
  - path: ../common/postgres/compose.yaml

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.24.0@sha256:4e3ea23c551706c6d7934e2b48e9c4015a60ef5d70f965d3f4e5b68d59ef6c95
    container_name: audiobookshelf
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/config:/config
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/metadata:/metadata
      - nfs-podcasts:/podcasts
    environment:
      - PORT=13378
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 1.5G
    expose:
      - "13378"

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.5.2@sha256:81d76b6c13a7a9481440402f0fa0ff1dc6027d003447da28eb1ed150e1846af7
    container_name: bazarr
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/bazarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
      - nfs-television:/media/television
    command:
      - --no-update=true
      - --config=/config
    entrypoint:
      - python3
      - /app/bazarr/bin/bazarr.py
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "6767"
    init: true

  lidarr:
    image: ghcr.io/linuxserver/lidarr:2.11.2@sha256:e01a6968d2c58f04278a67da9690e62b0cba07f5dbacb03b0cfbf195940f94a7
    container_name: lidarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/lidarr:/config
      - nfs-music:/media/music
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/lidarr/bin/Lidarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: .25G
        limits:
          memory: 2G
    expose:
      - "8686"
    init: true

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.37.0@sha256:68d16fa1a692ec26c4340a23f50b5980899c5630ce881fd0015dac849cbb9b53
    container_name: prowlarr
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/prowlarr:/config
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/prowlarr/bin/Prowlarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 512M
    expose:
      - "9696"
    init: true

  radarr:
    image: ghcr.io/linuxserver/radarr:5.25.0@sha256:36e43720c130ec2d3ed80726d2134af3c6644729f4750abc830fdda7fa71d1e1
    container_name: radarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/radarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/radarr/bin/Radarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G
    expose:
      - "7878"
    init: true

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:4.5.1@sha256:5a46efd411bd4c6d12706defe483ad1d34e36f758b44a15ae0be662f02c58194
    container_name: sabnzbd
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sabnzbd:/config
      - nfs-downloads:/downloads
    command:
      - --config-file
      - /config/sabnzbd.ini
      - -l1
    entrypoint:
      - python3
      - /app/sabnzbd/SABnzbd.py
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 128M
        limits:
          memory: 1G
    expose:
      - "8080"
    init: true

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.14@sha256:cdf5eb3cfa207d46b066bfbb41b03576c67a1f6ecc8aba19146d0f7349ec79dc
    container_name: sonarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sonarr:/config
      - nfs-downloads:/downloads
      - nfs-television:/media/television
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/sonarr/bin/Sonarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G
    expose:
      - "8989"
    init: true
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:2025.06.01@sha256:6cf97da47f4a87a83f28c19f9e16e70007629acc087311b2090452a2ca2aa37f
    container_name: ytdl-sub
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/ytdl-sub:/config
      - nfs-downloads:/downloads
      - nfs-internet:/internet
    environment:
      - PUID=3005
      - PGID=100
      - TZ=America/Los_Angeles
    entrypoint:
      - sleep
      - infinity
    restart: unless-stopped
    labels:
      - deck-chores.scheduled-task.command=sh -c "/config/scheduled-task >
        /proc/1/fd/1 2> /proc/1/fd/2"
      - deck-chores.scheduled-task.cron=*/12 0 0
      - deck-chores.scheduled-task.jitter=90m
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 500M
        limits:
          memory: 1G
    init: false

volumes:
  nfs-downloads:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/downloads"
  nfs-internet:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/internet"
  nfs-movies:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/movies"
  nfs-music:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/music"
  nfs-television:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/television"
  nfs-podcasts:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/podcasts"
