name: media

include:
  - path: ../common/postgres/compose.yaml

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.23.0@sha256:2d8bee3e87e860d67e11e13b5c42d97cb1fe071de53dea5502b3a9292e75e024
    container_name: audiobookshelf
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/config:/config
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/audiobookshelf/metadata:/metadata
      - nfs-podcasts:/podcasts
    environment:
      - PORT=13378
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 1.5G
    expose:
      - "13378"

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.5.2@sha256:558d6ddf36cd87bac5d4fb2ee8488730c4f65718961ef4ca7073062378aa7641
    container_name: bazarr
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/bazarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
      - nfs-television:/media/television
    command:
      - --no-update=true
      - --config=/config
    entrypoint:
      - python3
      - /app/bazarr/bin/bazarr.py
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "6767"
    init: true

  lidarr:
    image: ghcr.io/linuxserver/lidarr:2.11.2@sha256:3a7d5f70fec9f694eedfef7241a5cf6e2723bf280f1320d8f6b7fba44b14032e
    container_name: lidarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/lidarr:/config
      - nfs-music:/media/music
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/lidarr/bin/Lidarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: .25G
        limits:
          memory: 2G
    expose:
      - "8686"
    init: true

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.35.1@sha256:85718606c75bc0924921cb2df05b0f81c8a691952d44a5bc9f9946254493d1b4
    container_name: prowlarr
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/prowlarr:/config
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/prowlarr/bin/Prowlarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 512M
    expose:
      - "9696"
    init: true

  radarr:
    image: ghcr.io/linuxserver/radarr:5.22.4@sha256:105b7ffb9e88880a55a3fcd6116542f19af21aae8884a4e276e007d2816bbacb
    container_name: radarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/radarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/media/movies
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/radarr/bin/Radarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G
    expose:
      - "7878"
    init: true

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:4.5.1@sha256:913d57a64e9c9039c758b8f80e13226c3e226f7ffec34fbc56702421ace4c48c
    container_name: sabnzbd
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sabnzbd:/config
      - nfs-downloads:/downloads
    command:
      - --config-file
      - /config/sabnzbd.ini
      - -l1
    entrypoint:
      - python3
      - /app/sabnzbd/SABnzbd.py
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 128M
        limits:
          memory: 1G
    expose:
      - "8080"
    init: true

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.14@sha256:cdf5eb3cfa207d46b066bfbb41b03576c67a1f6ecc8aba19146d0f7349ec79dc
    container_name: sonarr
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/sonarr:/config
      - nfs-downloads:/downloads
      - nfs-television:/media/television
    command:
      - -nobrowser
      - -data=/config
    entrypoint:
      - /app/sonarr/bin/Sonarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 2G
    expose:
      - "8989"
    init: true
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:2025.05.05@sha256:623c47a0fc8121b6bac5baea6de779aa7dfa797707a339ad9f4aab2f9b2201f2
    container_name: ytdl-sub
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/ytdl-sub:/config
      - nfs-downloads:/downloads
      - nfs-internet:/internet
    environment:
      - PUID=3005
      - PGID=100
      - TZ=America/Los_Angeles
    entrypoint:
      - sleep
      - infinity
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 500M
        limits:
          memory: 1G
    init: false

volumes:
  nfs-downloads:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/downloads"
  nfs-internet:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/internet"
  nfs-movies:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/movies"
  nfs-music:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/music"
  nfs-television:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/television"
  nfs-podcasts:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/podcasts"
