name: home-automation

include:
  - path: ../common/postgres/compose.yaml # home-assistant database

services:
  go2rtc:
    image: alexxit/go2rtc@sha256:7d31dcb73633310e80497c431f4534c81ed55ec0708db3262bc56918e654bba5
    container_name: go2rtc
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/go2rtc:/config
    ports:
      # rtsp
      - "0.0.0.0:8554:8554"
      # webrtc
      - "0.0.0.0:8555:8555"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.go2rtc.loadbalancer.server.port=1984
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 32M
        limits:
          memory: 64M
    expose:
      - "1984"

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2025.7@sha256:e876528e4159974e844bbf3555e67ff48d73a78bf432b717dd9d178328230b40
    container_name: home-assistant
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/home-assistant/config:/config
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/home-assistant/backups:/backups
      - nfs-security:/mnt/security
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    command:
      - --config
      - /config
    entrypoint:
      - exec
      - python3
      - -m
      - homeassistant
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - metrics-job=home-assistant
      - scrape-port=8123
      - scrape-path=/api/prometheus
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 1G
    expose:
      - "8123"
    init: true

  mosquitto:
    image: registry-1.docker.io/library/eclipse-mosquitto:2.0.22@sha256:75042dd2dd262dff9eb29c47da26d8ee57211a7bc6fc51bae55badc5fc9f6724
    container_name: mosquitto
    ports:
      - "0.0.0.0:1883:1883"
    command:
      - -c
      - /mosquitto-no-auth.conf
    entrypoint:
      - mosquitto
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 16M
        limits:
          memory: 64M
    init: true

  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.5.1@sha256:1e639d3144960f246dcecc21d993169fd6844b5817e939bca498b2abf2c23159
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/zigbee2mqtt:/app/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    devices:
      - ${ZIGBEE_DEVICE:?}:/dev/zigbee
    expose:
      - "8080"

volumes:
  nfs-security:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/security"
