name: home-automation

include:
  - path: ../common/postgres/compose.yaml # home-assistant database

services:
  go2rtc:
    image: alexxit/go2rtc@sha256:7d31dcb73633310e80497c431f4534c81ed55ec0708db3262bc56918e654bba5
    container_name: go2rtc
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/go2rtc:/config
    ports:
      # rtsp
      - "0.0.0.0:8554:8554"
      # webrtc
      - "0.0.0.0:8555:8555"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.go2rtc.loadbalancer.server.port=1984
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 32M
        limits:
          memory: 64M
    expose:
      - "1984"

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2025.6@sha256:e207929bdf5dc95db43c618b877364e99f7ad506ec5440aeef80d5c9c1cae668
    container_name: home-assistant
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/home-assistant/config:/config
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/home-assistant/backups:/backups
      - nfs-security:/mnt/security
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    command:
      - --config
      - /config
    entrypoint:
      - exec
      - python3
      - -m
      - homeassistant
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - metrics-job=home-assistant
      - scrape-port=8123
      - scrape-path=/api/prometheus
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 256M
        limits:
          memory: 1G
    expose:
      - "8123"
    init: true

  mosquitto:
    image: registry-1.docker.io/library/eclipse-mosquitto:2.0.21@sha256:94f5a3d7deafa59fa3440d227ddad558f59d293c612138de841eec61bfa4d353
    container_name: mosquitto
    ports:
      - "0.0.0.0:1883:1883"
    command:
      - -c
      - /mosquitto-no-auth.conf
    entrypoint:
      - mosquitto
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 16M
        limits:
          memory: 64M
    init: true

  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.5.0@sha256:ff3c986b2c9ff796666f11d308e7e0782f13f3d03f57c5795c55b053ff2e7ec8
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/zigbee2mqtt:/app/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 128M
    devices:
      - ${ZIGBEE_DEVICE:?}:/dev/zigbee
    expose:
      - "8080"

volumes:
  nfs-security:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/security"
