services:
  discord-bot:
    image: ghcr.io/nalabelle/discord-bot:main-20220927080556@sha256:0eb8df9ef5c1d1d068338c07a6a4925e11df172a0aa27a09fa51828fc251646f
    container_name: discord-bot
    restart: unless-stopped
    command:
      - --config
      - /app/config/config.yaml
    secrets:
      - source: DISCORD_API_TOKEN
        target: /secrets/discord_api_token
      - source: FORECAST_API_KEY
        target: /secrets/forecast_api_key
      - source: GOOGLE_API_KEY
        target: /secrets/google_api_key
      - source: GOOGLE_CLIENT_ID
        target: /secrets/google_client_id
      - source: GOOGLE_CLIENT_SECRET
        target: /secrets/google_client_secret
    volumes:
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
      - ${VOLUMES?}/discord-bot/config:/app/config
      - ${VOLUMES?}/discord-bot/data:/app/data
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          cpus: "0.01"
          memory: 24M

secrets:
  DISCORD_API_TOKEN:
    environment: SERVICES__DISCORD_BOT__DISCORD_API_TOKEN
  FORECAST_API_KEY:
    environment: SERVICES__DISCORD_BOT__FORECAST_API_KEY
  GOOGLE_API_KEY:
    environment: SERVICES__DISCORD_BOT__GOOGLE_API_KEY
  GOOGLE_CLIENT_ID:
    environment: SERVICES__DISCORD_BOT__GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET:
    environment: SERVICES__DISCORD_BOT__GOOGLE_CLIENT_SECRET
