groups:
  - name: Dead Ringer
    rules:
      - alert: PushMonitor
        expr: 1
        annotations:
          summary: "Always firing alert"
          description: "Ensures the alerting component is working"
  - name: Hosts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
