scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Only keep networks exposed via proxy net.
      - source_labels: [__meta_docker_network_name]
        regex: proxy-.+
        action: keep
      # Only keep containers that have a `metrics-job` label.
      - source_labels: [__meta_docker_container_label_metrics_job]
        regex: .+
        action: keep
      # Change metrics_path to labeled value
      - source_labels: [__meta_docker_container_label_scrape_path]
        regex: (.+)
        target_label: __metrics_path__
      # Change port
      - source_labels: [__address__, __meta_docker_container_label_scrape_port]
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      # Use the task labels that are prefixed by `metrics-`.
      - regex: __meta_docker_container_label_metrics_(.+)
        action: labelmap
        replacement: $1
      # Keep specific task labels
      - regex: __meta_docker_network_label_com_docker_compose_(project|image)
        replacement: compose_$1
        action: labelmap
      - regex: container_label_org_opencontainers_image_(version|title)
        replacement: image_$1
        action: labelmap
  - job_name: file
    file_sd_configs:
      - files:
          - "/storage/_targets/*.yaml"
