services:
  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    container_name: ofelia
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - $DOCKER_SOCKET:/var/run/docker.sock:ro

  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    user: "0:0"
    entrypoint: sleep
    hostname: compose-$BACKUP_HOSTNAME
    command:
      - infinity
    restart: "unless-stopped"
    volumes:
      - ${VOLUMES?}/volumes:/volumes:ro
      # Don't put kopia in with the volumes or it'll loop itself
      - $HOME/.kopia:/app
    environment:
      KOPIA_PERSIST_CREDENTIALS_ON_CONNECT: "true"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.db-backup.schedule: "@every 12h"
      ofelia.job-exec.db-backup.command: "kopia snapshot create /volumes"
