name: system

services:
  alloy:
    image: registry-1.docker.io/grafana/alloy:v1.8.3@sha256:ab04df3936e4d71d31b6f55e0c58a7e749091f59635dd8c2bc731ba1b6c93701
    container_name: ${HOSTNAME:?}-alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: alloy-config
        target: /etc/alloy/alloy.config
    secrets:
      - alloy-api-key
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/alloy.config
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 32M
        limits:
          memory: 64M
    expose:
      - "12345"
    hostname: ${HOSTNAME:?}-alloy

  kopia:
    image: kopia/kopia:latest@sha256:615b786bdb46d5a9301338983e8077e5be0f1c643b7a3188c8732989104accf4
    container_name: kopia
    volumes:
      - ${VOLUMES:?}:/volumes:ro
      - kopia-cache:/app/cache
    configs:
      - source: kopia-backup
        target: /usr/local/bin/kopia-backup
    environment:
      KOPIA_LOG_DIR: /app/logs
      KOPIA_CACHE_DIRECTORY: /app/cache
      KOPIA_SERVER_ADDRESS:
      KOPIA_PASSWORD:
    command:
      - infinity
    entrypoint: sleep
    restart: unless-stopped
    user: "0:0"
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 24M
        limits:
          memory: 512M
    init: true

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1@sha256:d00a542e409ee618a4edc67da14dd48c5da66726bbd5537ab2af9c1dfc442c8a
    container_name: ${HOSTNAME:?}-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/l\
        ib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)(\
        $$|/)"
    restart: unless-stopped
    labels:
      - metrics-job=node
      - scrape-port=9100
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M
        limits:
          memory: 96M
    expose:
      - "9100"

  oom:
    image: registry-1.docker.io/library/docker:cli@sha256:3c69ee4af37c4efc954a29aeeb063f2194f3764851239e1fdbaa39c9dfe1157d
    container_name: oom
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - events
      - --filter
      - type=container
      - --filter
      - event=oom
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 7M
        limits:
          memory: 30M
    init: true

secrets:
  alloy-api-key:
    environment: ALLOY_API_KEY

configs:
  alloy-config:
    file: ./alloy.config
  kopia-backup:
    file: ./kopia-backup

volumes:
  kopia-cache: {}
