#!/bin/env bash
set -eu
set -o pipefail

kopia repository connect server \
  --override-hostname="compose"

for dir in /volumes/*/; do
  # Remove trailing /
  dir=${dir%*/}
  # Remove everything before and including the last /
  source=${dir##*/}

  kopia snapshot create \
    --override-source="/$source" \
    "$dir"
done
