services:
  traefik:
    container_name: traefik
    image: "traefik:v3.2@sha256:66e37237b371f2b25ce5f247cc371976929dcb18c041e05685f1de1df6422b72"
    restart: always
    init: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: Host(`${HOSTNAME:?}.${DOMAIN:?}`)
      traefik.http.routers.traefik.service: traefik
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
      traefik.tls.stores.default.defaultgeneratedcert.resolver: "letsencrypt"
      traefik.tls.stores.default.defaultgeneratedcert.domain.main: "${DOMAIN:?}"
      traefik.tls.stores.default.defaultgeneratedcert.domain.sans: "*.${DOMAIN:?}"

    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --api.dashboard=true
      - --api.insecure=true
      - --api.disabledashboardad=true
      - --certificatesresolvers.letsencrypt=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL?}
      - --certificatesresolvers.letsencrypt.acme.storage=/data/letsencrypt-acme.json
      - --entrypoints.web=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN:?}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN:?}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultrule=Host(`{{ normalize .ContainerName}}.${DOMAIN:?}`)
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik-cf_dns_api_token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik-cf_zone_api_token
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 20M
        limits:
          memory: 50M
    ports:
      - "8000:80"
      - "4430:443"
      # Uncomment this to access traefik dashboard directly
      # - "8080:8080"
    secrets:
      - traefik-cf_dns_api_token
      - traefik-cf_zone_api_token
    volumes:
      - "${DOCKER_SOCKET?}:/var/run/docker.sock:ro"
      - "${VOLUMES?}/traefik-data:/data"

  scheduler:
    image: premoweb/chadburn:1.0.7@sha256:096be3c00f39db7d7d33763432456ab8bdc79f0f5da7ec20fec5ff071f3e841f
    restart: unless-stopped
    container_name: scheduler
    init: true
    command:
      - daemon
      - --config=/etc/scheduler/config.ini
    configs:
      - source: scheduler
        target: /etc/scheduler/config.ini
        mode: 0444
    volumes:
      - ${DOCKER_SOCKET?}:/var/run/docker.sock

  kopia:
    image: kopia/kopia:latest@sha256:51784ce0961940846f4f47cab2d4f58e2e0cb467de357f9a80279b149a00c06e
    container_name: kopia
    user: "0:0"
    init: true
    labels:
      - chadburn.enabled=true
      - chadburn.job-exec.db-backup.schedule="@every 12h"
      - chadburn.job-exec.db-backup.command="/usr/local/bin/kopia/backup"
    entrypoint: sleep
    command:
      - infinity
    restart: unless-stopped
    volumes:
      - ${VOLUMES?}:/${COMPOSE_PROJECT_NAME:?}:ro
      # Don't put kopia in with the volumes or it'll loop itself
      - ${CACHE?}/kopia/cache:/app/cache
      - ${CACHE?}/kopia/logs:/app/logs
    environment:
      KOPIA_LOG_DIR: /app/logs
      KOPIA_CACHE_DIRECTORY: /app/cache
      KOPIA_SNAPSHOT_PATH: /${COMPOSE_PROJECT_NAME:?}
    configs:
      - source: kopia-backup
        target: /usr/local/bin/kopia-backup
        mode: 0555
    secrets:
      - kopia-password
      - kopia-server-url

configs:
  scheduler:
    content: ""
  kopia-backup:
    file: ${CONFIGS?}/kopia/backup

secrets:
  kopia-server-url:
    file: ${SECRETS?}/common/kopia/server-url
  kopia-password:
    file: ${SECRETS?}/common/kopia/password
  traefik-cf_dns_api_token:
    file: ${SECRETS?}/common/proxy/cf_dns_api_token
  traefik-cf_zone_api_token:
    file: ${SECRETS?}/common/proxy/cf_zone_api_token
