services:
  agent:
    image: victoriametrics/vmagent:v1.106.0
    container_name: ${COMPOSE_PROJECT_NAME:?}-metrics
    # port: 8429
    labels:
      - traefik.enable=true
      - traefik.http.services.metrics.loadbalancer.server.port=8429
    restart: unless-stopped
    command:
      - -promscrape.config=/config/prometheus.yaml
      - -remoteWrite.url=${METRICS_LONG_TERM_STORAGE:?}
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/monitoring/vmagent:/vmagentdata
      - ${DOCKER_SOCKET?}:/var/run/docker.sock:ro
    configs:
      - source: scrape-configs
        target: /config/prometheus.yaml
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 32M
        limits:
          memory: 64M
configs:
  scrape-configs:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/common/monitoring/scrape-configs.yaml
