services:
  postgres:
    image: docker.io/postgres:17@sha256:f176fef320ed02c347e9f85352620945547a9a23038f02b57cf7939a198182ae
    container_name: ${COMPOSE_PROJECT_NAME:?}-postgres
    restart: unless-stopped
    init: true
    labels:
      - chadburn.enabled=true
      - chadburn.job-exec.db-backup.schedule=@every 12h
      - chadburn.job-exec.db-backup.command=/usr/local/bin/db-backup
      - chadburn.job-exec.db-backup.user=postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    expose:
      - 5432
    configs:
      - source: postgres_db-backup
        target: /usr/local/bin/db-backup
        mode: 0555
    secrets:
      - postgres_password
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 64M
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

configs:
  postgres_db-backup:
    file: ${CONFIGS:?}/common/postgres/db-backup

secrets:
  postgres_password:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/common/postgres/password
