# dclint disable require-project-name-field service-container-name-regex
services:
  postgres:
    image: docker.io/postgres:17@sha256:0ab5f0d74775b687e8cc67c3d55a7c8e2157c40a29171a48aefe6ce1cb3a2c3a
    container_name: ${COMPOSE_PROJECT_NAME:?}-postgres
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/postgres:/var/lib/postgresql/data
    configs:
      - source: postgres_db-backup
        target: /usr/local/bin/db-backup
        mode: 555
    secrets:
      - postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - chadburn.enabled=true
      - chadburn.job-exec.${COMPOSE_PROJECT_NAME:?}-db-backup.schedule=@every 12h
      - chadburn.job-exec.${COMPOSE_PROJECT_NAME:?}-db-backup.command=/usr/local/bin/db-backup
      - chadburn.job-exec.${COMPOSE_PROJECT_NAME:?}-db-backup.user=postgres
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "5432"
    init: true

secrets:
  postgres_password:
    file: ${SECRETS:?}/${COMPOSE_PROJECT_NAME:?}/common/postgres/password

configs:
  postgres_db-backup:
    file: ${CONFIGS:?}/common/postgres/db-backup
