name: proxy
services:
  traefik:
    volumes:
      - $HOME/.local/config/certs/_wildcard.compose.localhost-key.pem:/etc/traefik/certs/key.pem
      - $HOME/.local/config/certs/_wildcard.compose.localhost.pem:/etc/traefik/certs/cert.pem
      # Mount a dynamic configuration file for static TLS configuration
      - ./dev/traefik-dynamic.yaml:/etc/traefik/dynamic/conf.yaml
    secrets:
      - source: fake
        target: /run/secrets/traefik-cf_dns_api_token
      - source: fake
        target: /run/secrets/traefik-cf_zone_api_token
    ports:
      - "0.0.0.0:8080:8080"
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --api.dashboard=true
      - --api.insecure=true
      - --api.disabledashboardad=true
      - --certificatesresolvers.letsencrypt=false
      - --entrypoints.web=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      # Add file provider for static configuration
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultrule=Host(`{{ normalize .ContainerName
        }}.${DOMAIN:?}`)

secrets:
  fake:
    file: /dev/null
