services:
  traefik:
    container_name: traefik
    image: "traefik:v3.2@sha256:64473d350aeafa60257aed5f03eb6aec4558a2434d2cf8ab6f97fd3f5f8eb47c"
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.service: traefik
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
      traefik.tls.stores.default.defaultgeneratedcert.resolver: "letsencrypt"
      traefik.tls.stores.default.defaultgeneratedcert.domain.main: "${DOMAIN}"
      traefik.tls.stores.default.defaultgeneratedcert.domain.sans: "*.${DOMAIN}"
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --api.dashboard=true
      - --api.insecure=true
      - --api.disabledashboardad=true
      - --certificatesresolvers.letsencrypt=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.letsencrypt.acme.email=${PROXY__CERT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/data/letsencrypt-acme.json
      - --entrypoints.web=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultrule=Host(`{{ normalize .ContainerName}}.${DOMAIN}`)
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_dns_api_token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/cf_zone_api_token
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 20M
        limits:
          memory: 50M

    ports:
      - "8000:80"
      - "4430:443"
      # Uncomment this to access traefik dashboard directly
      # - "8080:8080"
    secrets:
      - cf_dns_api_token
      - cf_zone_api_token
    volumes:
      - "$DOCKER_SOCKET:/var/run/docker.sock:ro"
      - "${VOLUMES?}/traefik-data:/data"

  whoami:
    image: "traefik/whoami@sha256:43a68d10b9dfcfc3ffbfe4dd42100dc9aeaf29b3a5636c856337a5940f1b4f1c"
    restart: always
    container_name: "whoami"
    # port: 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"

secrets:
  cf_dns_api_token:
    environment: PROXY__CF_DNS_API_TOKEN
  cf_zone_api_token:
    environment: PROXY__CF_ZONE_API_TOKEN
