name: files
services:
  paperless:
    volumes:
      - local-documents:/documents
  photoprism:
    volumes:
      - local-photos:/photos
  stirling:
    volumes:
      - local-inbox:/pipeline/watchedFolders
      - local-processed:/pipeline/finishedfolders

volumes:
  local-inbox: {}
  local-processed: {}
  local-documents: {}
  local-photos: {}
  nfs-photos: {}
  nfs-documents: {}
