name: files

include:
  - path: ../common/postgres/compose.yaml
  - path: ../common/mariadb/compose.yaml

services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.17@sha256:ab72a0ab42a792228cdbe83342b99a48acd49f7890ae54b1ae8e04401fba24ee
    container_name: paperless
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/paperless:/config
      - nfs-documents:/documents
    secrets:
      - paperless-dbpass
    environment:
      PAPERLESS_CONSUMER_POLLING: "30"
      PAPERLESS_PORT: "8000"
      PAPERLESS_URL: https://paperless.${DOMAIN:?}
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBPASS: ${PAPERLESS_DBPASS:?}
      # PAPERLESS_DBPASS_FILE doesn't trim whitespace so is kinda useless
      PAPERLESS_DATA_DIR: /config/data
      PAPERLESS_MEDIA_ROOT: /documents
      PAPERLESS_CONSUMPTION_DIR: /documents/_processed
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_DATE_ORDER: MDY
      PAPERLESS_TASK_WORKERS: "2"
      PAPERLESS_THREADS_PER_WORKER: "2"
      PAPERLESS_EMAIL_TASK_CRON: "disable"
      PAPERLESS_ENABLE_COMPRESSION: "0"
      PAPERLESS_WEBSERVER_WORKERS: "2"
      USERMAP_UID: "3005"
      USERMAP_GID: "100"
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 24M
        limits:
          memory: 1G
    expose:
      - "8000"
    init: false

  photoprism:
    image: registry-1.docker.io/photoprism/photoprism:latest@sha256:2ba3a774ca1acc498096d7a5cb50df9cfecb7e3117a617d648093ff74eec2793
    container_name: photoprism
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/photoprism:/assets
      - nfs-photos:/photos
    configs:
      - source: photoprism-maintenance
        target: /app/scripts/maintain
    environment:
      HOME: /assets/config
      PHOTOPRISM_ADMIN_PASSWORD:
      PHOTOPRISM_CACHE_PATH: /assets/cache
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_DSN:
      PHOTOPRISM_DEBUG: true
      PHOTOPRISM_EXPORT_PATH: /photos/export
      PHOTOPRISM_HTTP_COMPRESSION: gzip
      PHOTOPRISM_HTTP_HOST: 0.0.0.0
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_IMPORT_PATH: /photos/import
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_ORIGINALS_PATH: /photos/Catalog
      PHOTOPRISM_SITE_URL: https://photoprism.${DOMAIN:?}
      PHOTOPRISM_STORAGE_PATH: /photos/Photoprism
      PHOTOPRISM_UMASK: "0002"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2342" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - traefik.enable=true
      - deck-chores.backup.command=photoprism backup -a -i -f
      - deck-chores.backup.cron=*/12 0 0
      - deck-chores.backup.jitter=30m
      - deck-chores.import.command=photoprism import
      - deck-chores.import.cron=* 0 0
      - deck-chores.import.jitter=5m
      - deck-chores.maintain.command=/app/scripts/maintain
      - deck-chores.maintain.cron=0 0 0
      - deck-chores.maintain.jitter=30m
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 128M
        limits:
          memory: 2G
    expose:
      - "2342"
    init: false

  redis:
    image: redis:alpine@sha256:73734b014e53b3067916918b70718ca188c16895511a272a020c9a71084eecda
    container_name: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 20s
      timeout: 3s
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - "6379"
    init: true

  stirling:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest-ultra-lite@sha256:47c91c9080308674ecb6be7c1e280c743240cef1f478af4cdad4a1b5ba636aa3
    container_name: stirling
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/stirling/trainingData:/usr/share/tessdata
      - type: tmpfs
        target: /configs
      - type: tmpfs
        target: /customFiles
      - type: tmpfs
        target: /logs
      - source: nfs-documents
        target: /pipeline/watchedFolders
        type: volume
        volume:
          subpath: _inbox
      - source: nfs-documents
        target: /pipeline/finishedfolders
        type: volume
        volume:
          subpath: _processed
    environment:
      LANGS: "en_GB,en_US,es_US"
      DOCKER_ENABLE_SECURITY: "false"
      SECURITY_ENABLELOGIN: "false"
      SYSTEM_DEFAULTLOCALE: en-US
      SYSTEM_GOOGLEVISIBILITY: "false"
      SYSTEM_ENABLEANALYTICS: "false"
      SHOW_SURVEY: "false"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP'"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 128M
        limits:
          memory: 256M
    expose:
      - "8080"

volumes:
  redis-data: {}
  nfs-photos:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/photos"
  nfs-documents:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/documents"

secrets:
  paperless-dbpass:
    environment: PAPERLESS_DBPASS

configs:
  photoprism-maintenance:
    file: ./photoprism-maintenance
