name: files

include:
  - path: ../common/compose.postgres.yaml
  - path: ../common/compose.mariadb.yaml

services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.15@sha256:39b337e73c978238f0b529baf42f1b59b65d17eed35cd61bc1ccbbf779b5d58b
    container_name: paperless
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/paperless:/config
      - nfs-documents:/documents
    secrets:
      - paperless-dbpass
    environment:
      PAPERLESS_CONSUMER_POLLING: "30"
      PAPERLESS_PORT: "8000"
      PAPERLESS_URL: https://paperless.${DOMAIN:?}
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBPASS: ${PAPERLESS_DBPASS:?}
      # PAPERLESS_DBPASS_FILE doesn't trim whitespace so is kinda useless
      PAPERLESS_DATA_DIR: /config/data
      PAPERLESS_MEDIA_ROOT: /documents
      PAPERLESS_CONSUMPTION_DIR: /documents/_processed
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_DATE_ORDER: MDY
      PAPERLESS_TASK_WORKERS: "2"
      PAPERLESS_THREADS_PER_WORKER: "2"
      PAPERLESS_EMAIL_TASK_CRON: "disable"
      PAPERLESS_ENABLE_COMPRESSION: "0"
      PAPERLESS_WEBSERVER_WORKERS: "2"
      USERMAP_UID: "3005"
      USERMAP_GID: "100"
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 24M
        limits:
          memory: 1G
    expose:
      - "8000"
    init: false

  pdf-web-edit:
    image: ghcr.io/danielhabenicht/danielhabenicht/fork.pdf-web-edit:v0.9.6@sha256:e851892cc1dc9d8d62c941d37a47057063d9d51d80ad9e95d07ce711259984be
    container_name: pdf-web-edit
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/pdf-web-edit:/config
      - source: nfs-documents
        target: /inbox
        type: volume
        volume:
          subpath: _inbox
      - source: nfs-documents
        target: /outbox
        type: volume
        volume:
          subpath: _processed
      - source: nfs-documents
        target: /archive
        type: volume
        volume:
          subpath: _rejected
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 24M
        limits:
          memory: 96M
    expose:
      - "8080"
    init: false

  photoprism:
    image: registry-1.docker.io/photoprism/photoprism:latest@sha256:19fdf0d52676d07abe63376a3b2d07779cac010a1bfca563af11968abd2df218
    container_name: photoprism
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/photoprism:/assets
      - nfs-photos:/photos
    configs:
      - source: photoprism-maintenance
        target: /app/scripts/maintain
    environment:
      HOME: /assets/config
      PHOTOPRISM_ADMIN_PASSWORD:
      PHOTOPRISM_CACHE_PATH: /assets/cache
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_DSN:
      PHOTOPRISM_DEBUG: true
      PHOTOPRISM_EXPORT_PATH: /photos/export
      PHOTOPRISM_HTTP_COMPRESSION: gzip
      PHOTOPRISM_HTTP_HOST: 0.0.0.0
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_IMPORT_PATH: /photos/import
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_ORIGINALS_PATH: /photos/Catalog
      PHOTOPRISM_SITE_URL: https://photoprism.${DOMAIN:?}
      PHOTOPRISM_STORAGE_PATH: /photos/Photoprism
      PHOTOPRISM_UMASK: "0002"
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 128M
        limits:
          memory: 2G
    expose:
      - "2342"
    init: false

  redis:
    image: redis:alpine@sha256:62b5498c91778f738f0efbf0a6fd5b434011235a3e7b5f2ed4a2c0c63bb1c786
    container_name: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - "6379"
    init: true

volumes:
  redis-data: {}
  nfs-photos:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/photos"
  nfs-documents:
    driver_opts:
      type: nfs
      o: "addr=${FILEHOST:?},nfsvers=4,rw,soft,noatime,nodiratime"
      device: ":/documents"

configs:
  photoprism-maintenance:
    file: ./photoprism-maintenance

secrets:
  paperless-dbpass:
    environment: PAPERLESS_DBPASS
