include:
  - ../postgres/compose.yaml

services:
  miniflux:
    image: miniflux/miniflux:latest@sha256:5950f5395ba02125c0d04b4287e6ab0467715112b9dcdc435ce89a52f595d473
    container_name: miniflux
    labels:
      - "traefik.enable=true"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - RUN_MIGRATIONS=1
      - "BASE_URL=https://miniflux.${DOMAIN?}"
      - POLLING_PARSING_ERROR_LIMIT=0
      - DATABASE_URL=${APPS__MINIFLUX__DATABASE_URL?}
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    # port: 8080
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 24M
        limits:
          memory: 128M
  miniflux-sidekick:
    container_name: miniflux-sidekick
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 128M
    image: ghcr.io/nalabelle/miniflux-sidekick:0.1.1729902975@sha256:8321665f43fe86f4e328bff2a30b5ed16499fc5192cc701697623d35c60b3a89
    environment:
      - MF_LOG_LEVEL=debug
      - MF_ENVIRONMENT=prod
      - MF_API_KEY=${APPS__MINIFLUX_SIDEKICK__API_KEY?}
      - MF_API_ENDPOINT=http://miniflux:8080
      - MF_KILLFILE_PATH=/config/killfile
      - MF_REFRESH_INTERVAL=*/1 * * * *
    volumes:
      - "${VOLUMES?}/miniflux-sidekick-config:/config"

  libreddit:
    # used to be libreddit, swapped to redlib
    image: quay.io/redlib/redlib:latest@sha256:a3f1eca3ebfc043eea4bc8274b1e9fe86ec15d0efa13536bd519f36eb18f763d
    restart: unless-stopped
    container_name: libreddit
    environment:
      - REDLIB_DEFAULT_THEME=black
    labels:
      - "traefik.enable=true"
    # ports: 8080
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M

  wallabag:
    image: wallabag/wallabag@sha256:d482b139bab164afef0e8bbfbeb7c55cd3e10e848b95d7d167e4ffcbc847f4b9
    restart: unless-stopped
    container_name: wallabag
    labels:
      - "traefik.enable=true"
    environment:
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=postgres
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${APPS__WALLABAG__POSTGRES_PASSWORD?}
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_USER=${APPS__WALLABAG__POSTGRES_USERNAME?}
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.${DOMAIN?}
    # ports: 80
    volumes:
      - ${CONFIG?}/wallabag/99-custom.ini:/etc/php81/conf.d/99-custom.ini
      - ${VOLUMES?}/wallabag/data:/var/www/wallabag/data
      - ${VOLUMES?}/wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/api/info",
        ]
      interval: 1m
      timeout: 3s
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine@sha256:de13e74e14b98eb96bdf886791ae47686c3c5d29f9d5f85ea55206843e3fce26
    container_name: redis
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

  grist:
    image: registry-1.docker.io/gristlabs/grist:1.2.0@sha256:0760be099f4d5c9e14f38748b2c2b28e5a44480c9590641c198bb16e69fb7973
    container_name: grist
    environment:
      - APP_HOME_URL=https://grist.${DOMAIN?}
      - GRIST_SINGLE_ORG=${ORG?}
    labels:
      - "traefik.enable=true"
    entrypoint:
      - node
      - ./sandbox/supervisor.mjs
    #ports: 8484
    volumes:
      - ${VOLUMES?}/grist:/persist
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 64M
        limits:
          memory: 512M
