name: apps

include:
  - path: ../common/postgres/compose.yaml

services:
  grist:
    image: registry-1.docker.io/gristlabs/grist:1.5.2@sha256:f326d59774db6caf1ad09c34c9fc8d2f67741f0dd237ff9ae3470f875ffd452e
    container_name: grist
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/grist:/persist
    environment:
      - APP_HOME_URL=https://grist.${DOMAIN:?}
      - GRIST_SINGLE_ORG=${GRIST_ORG:?}
    entrypoint:
      - node
      - ./sandbox/supervisor.mjs
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "8484"
    init: true

  # used to be libreddit, swapped to redlib
  libreddit:
    image: quay.io/redlib/redlib:latest@sha256:8c6c56472380188edc8dcd15b1a8e6741281635446b95c6ef1222f9940a96d93
    container_name: libreddit
    environment:
      - REDLIB_DEFAULT_THEME=black
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "--tries=1",
          "http://localhost:8080/settings"
        ]
      interval: 1m
      timeout: 3s
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - "8080"
    init: true

  miniflux:
    image: miniflux/miniflux:latest@sha256:3a11ac10969ec406d90eb9f2cec04e7d3b89bd9bc728bab6f036f604c4396f1c
    container_name: miniflux
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - miniflux-database_url
    environment:
      - BASE_URL=https://miniflux.${DOMAIN:?}
      - DATABASE_URL_FILE=/run/secrets/miniflux-database_url
      - METRICS_ALLOWED_NETWORKS=127.0.0.1/8,172.0.0.1/8
      - METRICS_COLLECTOR=1
      - POLLING_FREQUENCY=180 #Minutes
      - POLLING_PARSING_ERROR_LIMIT=99
      - RUN_MIGRATIONS=1
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD"
        - "/usr/bin/miniflux"
        - "-healthcheck"
        - "auto"
    labels:
      - metrics-job=miniflux
      - scrape-port=8080
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.03"
          memory: 24M
        limits:
          memory: 128M
    expose:
      - "8080"
    init: true

  miniflux-sidekick:
    image: ghcr.io/nalabelle/miniflux-sidekick:0.1.1746559476@sha256:132707a226bae54e0a742f477ad967a44f13d2da11ce27f1e425743f14d62b1e
    depends_on:
      miniflux:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/miniflux-sidekick:/config
    environment:
      MF_API_ENDPOINT: http://miniflux:8080
      MF_API_KEY: ${MINIFLUX_SIDEKICK_API_KEY:?}
      MF_ENVIRONMENT: prod
      MF_KILLFILE_PATH: /config/killfile
      MF_LOG_LEVEL: debug
      MF_REFRESH_INTERVAL: "*/1 * * * *"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 128M
    init: true

  redis:
    image: redis:alpine@sha256:62b5498c91778f738f0efbf0a6fd5b434011235a3e7b5f2ed4a2c0c63bb1c786
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD"
        - "redis-cli"
        - "ping"
      interval: 20s
      timeout: 3s
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - "6379"
    init: true

  wallabag:
    image: wallabag/wallabag@sha256:9989e05769885aef0b316508b728580460c7713e435cc0b02c16e7b06e17bb6a
    container_name: wallabag
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/wallabag/data:/var/www/wallabag/data
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/wallabag/images:/var/www/wallabag/web/assets/images
    configs:
      - source: wallabag_99-custom
        target: /etc/php81/conf.d/99-custom.ini
        mode: 444
    environment:
      SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
      SYMFONY__ENV__DATABASE_HOST: postgres
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_PASSWORD: ${WALLABAG_DATABASE_PASSWORD:?}
      SYMFONY__ENV__DATABASE_PORT: 5432
      SYMFONY__ENV__DATABASE_USER: ${WALLABAG_DATABASE_USER:?}
      SYMFONY__ENV__DOMAIN_NAME: https://wallabag.${DOMAIN:?}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/api/info"
        ]
      interval: 1m
      timeout: 3s
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - "80"
    init: true

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:?}
    enable_ipv6: true

secrets:
  miniflux-database_url:
    environment: MINIFLUX_DATABASE_URL

configs:
  wallabag_99-custom:
    content: |
      memory_limit=800M
