name: apps

include:
  - path: ../common/postgres/compose.yaml

services:
  grist:
    image: registry-1.docker.io/gristlabs/grist:1.7.2@sha256:b7957412adaafba5eb43b13b9a40f5a67b3b72f2da02a4045d4008fa26d1365f
    container_name: grist
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/grist:/persist
    environment:
      - APP_HOME_URL=https://grist.${DOMAIN:?}
      - GRIST_SINGLE_ORG=${GRIST_ORG:?}
    entrypoint:
      - node
      - ./sandbox/supervisor.mjs
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 64M
        limits:
          memory: 512M
    expose:
      - "8484"
    init: true

  # used to be libreddit, swapped to redlib
  libreddit:
    image: quay.io/redlib/redlib:latest@sha256:3908c592bba4a17d32516277504c42284600bd826cf1c1f9a309fdedc7bdd27a
    container_name: libreddit
    environment:
      - REDLIB_DEFAULT_THEME=black
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "--tries=1",
          "http://localhost:8080/settings"
        ]
      interval: 1m
      timeout: 3s
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - "8080"
    init: true

  miniflux:
    image: miniflux/miniflux:latest@sha256:d8e0f95eaa319211642e22e7ee78f59b1c224071b40670635ad29c4f04e7b036
    container_name: miniflux
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - miniflux-database_url
    environment:
      - BASE_URL=https://miniflux.${DOMAIN:?}
      - DATABASE_URL_FILE=/run/secrets/miniflux-database_url
      - METRICS_ALLOWED_NETWORKS=127.0.0.1/8,172.0.0.1/8
      - METRICS_COLLECTOR=1
      - POLLING_FREQUENCY=180 #Minutes
      - POLLING_PARSING_ERROR_LIMIT=99
      - RUN_MIGRATIONS=1
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD"
        - "/usr/bin/miniflux"
        - "-healthcheck"
        - "auto"
    labels:
      - metrics-job=miniflux
      - scrape-port=8080
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.03"
          memory: 24M
        limits:
          memory: 128M
    expose:
      - "8080"
    init: true

  miniflux-filter:
    image: ghcr.io/nalabelle/miniflux-filter:sha-4e90dc7@sha256:c91ad1dc2ad67e8bfb67520b65819c868b6e2d0184f4a86cca922507e7d5d092
    container_name: miniflux-filter
    depends_on:
      miniflux:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/miniflux-filter:/app/rules
    environment:
      MINIFLUX_URL: http://miniflux:8080
      MINIFLUX_API_TOKEN: ${MINIFLUX_FILTER_API_TOKEN:?}
      MINIFLUX_FILTER_WEB_ENABLED: "true"
      MINIFLUX_FILTER_WEB_PORT: "8080"
      MINIFLUX_FILTER_POLL_INTERVAL: "120"
      MINIFLUX_FILTER_RULES_DIR: /app/rules
    restart: unless-stopped
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 128M
    expose:
      - "8080"
    init: true

  redis:
    image: redis:alpine@sha256:7521abdff715d396aa482183942f3fe643344287c29ccb66eee16ac08a92190f
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD"
        - "redis-cli"
        - "ping"
      interval: 20s
      timeout: 3s
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - "6379"
    init: true

  wallabag:
    image: wallabag/wallabag@sha256:efa1c00736e0544291dd104f8f3092ca5e88076862e9e034ae9cd3eaa9d36daa
    container_name: wallabag
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/wallabag/data:/var/www/wallabag/data
      - ${VOLUMES:?}/${COMPOSE_PROJECT_NAME:?}/wallabag/images:/var/www/wallabag/web/assets/images
    configs:
      - source: wallabag_99-custom
        target: /etc/php81/conf.d/99-custom.ini
        mode: 444
    environment:
      SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
      SYMFONY__ENV__DATABASE_HOST: postgres
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_PASSWORD: ${WALLABAG_DATABASE_PASSWORD:?}
      SYMFONY__ENV__DATABASE_PORT: 5432
      SYMFONY__ENV__DATABASE_USER: ${WALLABAG_DATABASE_USER:?}
      SYMFONY__ENV__DOMAIN_NAME: https://wallabag.${DOMAIN:?}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/api/info"
        ]
      interval: 1m
      timeout: 3s
    labels:
      - traefik.enable=true
    deploy:
      resources:
        reservations:
          cpus: "0.02"
          memory: 20M
        limits:
          memory: 256M
    expose:
      - "80"
    init: true

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:?}
    enable_ipv6: true

secrets:
  miniflux-database_url:
    environment: MINIFLUX_DATABASE_URL

configs:
  wallabag_99-custom:
    content: |
      memory_limit=${WALLABAG_MEMORY_LIMIT:?}
