include:
  - ../postgres/compose.yaml

services:
  miniflux:
    image: miniflux/miniflux:latest@sha256:5950f5395ba02125c0d04b4287e6ab0467715112b9dcdc435ce89a52f595d473
    container_name: miniflux
    labels:
      - "traefik.enable=true"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - RUN_MIGRATIONS=1
      - "BASE_URL=https://miniflux.${DOMAIN}"
      - POLLING_PARSING_ERROR_LIMIT=0
      - DATABASE_URL=${APPS__MINIFLUX__DATABASE_URL}
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
