include:
  - ../system/compose.yaml

services:
  postgres:
    container_name: postgres
    image: docker.io/postgres:17@sha256:8d3be35b184e70d81e54cbcbd3df3c0b47f37d06482c0dd1c140db5dbcc6a808
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    # port: 5432
    deploy:
      resources:
        reservations:
          cpus: "0.05"
          memory: 64M
        limits:
          memory: 512M
    secrets:
      - postgres_password
    volumes:
      - "${PWD?}/files/postgres/db-backup:/usr/local/bin/db-backup"
      - "${VOLUMES?}/postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.db-backup.schedule: "@every 12h"
      ofelia.job-exec.db-backup.user: "postgres"
      ofelia.job-exec.db-backup.command: "/usr/local/bin/db-backup"

secrets:
  postgres_password:
    environment: POSTGRES__POSTGRES_PASSWORD
